---
- hosts: NAS
  sudo: true

  vars:
    # Username
    user: nas
    # Timezone
    timezone: 'Europe/Paris'
    locale: en_US.UTF-8
    download_dir: /media/esata/dl/transmission
    path_ansible_files: /home/{{ user }}/.ansible/
    path_share: /media



  tasks:

    ###################
    # User Management
    ###################
    - name: Create user {{ user }}
      user: name={{ user }}
            comment="{{ user }} user"
            shell=/bin/bash

    - name: Add {{ user }} to sudoers
      template: src=templates/sudoers-user.j2
                dest=/etc/sudoers.d/{{ user }}-sudoer
                owner=root
                mode=0440
                group=root
                validate='visudo -cf %s'

    - name: Add my public key to {{ user }}
      authorized_key: user={{ user }}
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


    ###########################
    # Install python dep for ansible
    ###########################
    - name: Create {{ path_ansible_files }} directory
      file: path={{ path_ansible_files }} state=directory  owner={{ user }} group={{ user }}
    - name: Bootstrap for ansible (various dep)
      shell: sudo apt-get -y install python-apt python-pycurl && touch "{{ path_ansible_files}}.bootstrap"
      args:
        creates: "{{ path_ansible_files}}.bootstrap"


    ###################
    # Locale Management
    ###################
    - name: generate locale
      shell: locale-gen {{ locale }} && touch {{ path_ansible_files}}.locales_gen
      args:
        creates: "{{ path_ansible_files}}.locales_gen"

    - name: reconfigure locales
      shell:  dpkg-reconfigure locales && touch {{ path_ansible_files}}.locales_reconf
      args:
        creates: "{{ path_ansible_files}}.locales_reconf"


    ###################
    # Time management
    ###################
    - name: Set local timezone
      copy: content={{ timezone }}
            dest=/etc/timezone
      notify: update tzdata

    - name: Install NTP
      apt: name=ntp state=present

    - name: Start the ntp service
      service: name=ntp state=started enabled=true

    ###################
    # Misc. tools
    ###################
    - name: Install usefull system tools
      apt: name={{ item }} state=present
      with_items:
        - vim
        - htop
        - git
        - tig
        - ncdu
        - python-pip

    ######################
    # Drives management
    ######################
    - name: Create directory to mount the drives
      file: path=/media/esata/dl state=directory  owner={{ user }} group={{ user }}
      file: path=/media/esata/backup state=directory owner={{ user }} group={{ user }}


    - name: Apply the correct fstab
      copy: src=files/fstab.cubi dest=/etc/fstab backup=yes

    ###################
    # Transmission
    ###################  
    - name: Install transmission
      apt: name={{ item }} state=present
      with_items:
        - transmission-cli
        - transmission-common
        - transmission-daemon

    - name: Stop the transmission service
      service: name=transmission-daemon state=stopped enabled=true

    - name: Configure transmission
      template: src=templates/transmission.conf.j2 dest=/etc/transmission-daemon/settings.json backup=yes owner=debian-transmission
      notify:
        - restart transmission

    ##################
    # Shares
    ##################

    - name: Install sharing programs
      apt: name={{ item }} state=present
      with_items:
        - samba
        - nfs-kernel-server

    - name: Configure samba
      template: src=templates/samba.conf.j2 dest=/etc/samba/smb.conf 
      notify: 
        - restart samba

    - name: Configure nfs
      template: src=templates/nfs.conf.j2 dest=/etc/exports
      notify:
        - restart nfs

    ############################
    # Monitoring
    ############################

    # Ajenti : https://ip:8000
    - name: Download Ajenti key
      apt_key: url=http://repo.ajenti.org/debian/key
    
    - name: Add Ajenti repository to the list of repositories and update cache
      apt_repository: repo='deb http://repo.ajenti.org/debian main main debian' update_cache=true state=present
    
    - name: Install monitoring tools
      apt: name={{ item }} state=present 
      with_items: 
        - ajenti
        - supervisor
        - monit
      notify:
        - restart ajenti
        - restart supervisor

    - name: Configure monit
      copy: src=files/monit.conf dest=/etc/monit/monitrc backup=yes
      notify:
        - restart monit

   ###################
  # Handlers
  ###################
  handlers:
    - name: reload iptables
      action: shell /sbin/iptables-restore < /etc/iptables.up
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
    - name: restart supervisor
      service: name=supervisor state=restarted enabled=yes
    - name: restart transmission
      service: name=transmission-daemon state=restarted enabled=yes
    - name: restart ajenti
      service: name=ajenti state=restarted enabled=yes
    - name: restart samba
      service: name=samba state=restarted enabled=yes
    - name: restart supervisor
      service: name=supervisor state=started enabled=true
    - name: restart nfs
      service: name=nfs-kernel-server state=restarted enabled=yes
    - name: restart monit
      service: name=monit state=restarted enabled=yes